version: '3.7'
services:
    db:
        container_name: 'NYT'
        environment:
            POSTGRES_USER: sergio
            POSTGRES_DB: sergio
            POSTGRES_PASSWORD: sergio
        image: postgres:13-alpine
        ports:
            - 5432:5432
        volumes:
            - db-data:/var/lib/postgres/data

volumes:
    db-data: {}
